# Generated by Django 3.2.12 on 2024-06-26 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('categoria', models.SmallIntegerField(choices=[(1, 'Estudos'), (2, 'Lazer'), (3, 'Alimentação'), (4, 'Moradia'), (5, 'Transporte'), (6, 'Viagens'), (7, 'Empréstimo'), (8, 'Manutenção'), (9, 'Outros')])),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_compra', models.DateField()),
                ('tipo_pagamento', models.SmallIntegerField(choices=[(1, 'Á vista'), (2, 'Parcelada'), (3, 'Assinatura'), (7, 'Outros')])),
                ('banco', models.SmallIntegerField(choices=[(1, 'Nubank'), (2, 'Inter'), (3, 'C6'), (4, 'Neon'), (5, 'PicPay'), (6, 'Banco do Brasil'), (7, 'Outros')])),
                ('parcelas_totais', models.SmallIntegerField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_feitos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
