# Generated by Django 3.2.12 on 2024-06-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='tipo_pagamento',
            field=models.SmallIntegerField(choices=[(1, 'Á vista'), (2, 'Parcelada'), (3, 'Assinatura')]),
        ),
    ]
