# Generated by Django 3.2.12 on 2024-06-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0002_alter_gasto_tipo_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='tipo_pagamento',
            field=models.SmallIntegerField(choices=[(1, 'À vista'), (2, 'Parcelada'), (3, 'Assinatura')]),
        ),
    ]
